/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiProxyImageRouteImport } from './routes/api.proxy-image'
import { Route as AppTrackedRouteImport } from './routes/_app.tracked'
import { Route as AppTopListsRouteImport } from './routes/_app.top-lists'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompareRouteImport } from './routes/_app.compare'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppAnalyzeRouteImport } from './routes/_app.analyze'
import { Route as AppReportIdRouteImport } from './routes/_app.report.$id'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as AppReportIdIndexRouteImport } from './routes/_app.report.$id.index'
import { Route as ApiPublicHooksProcessJobsRouteImport } from './routes/api.public.hooks.process-jobs'
import { Route as AppReportIdReachRouteImport } from './routes/_app.report.$id.reach'
import { Route as AppReportIdGrowthRouteImport } from './routes/_app.report.$id.growth'
import { Route as AppReportIdEngagementRouteImport } from './routes/_app.report.$id.engagement'
import { Route as AppReportIdContentRouteImport } from './routes/_app.report.$id.content'
import { Route as AppReportIdBrandRouteImport } from './routes/_app.report.$id.brand'
import { Route as AppReportIdAudienceRouteImport } from './routes/_app.report.$id.audience'
import { Route as AppReportIdAiRouteImport } from './routes/_app.report.$id.ai'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy-image',
  path: '/api/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackedRoute = AppTrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => AppRoute,
} as any)
const AppTopListsRoute = AppTopListsRouteImport.update({
  id: '/top-lists',
  path: '/top-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppReportIdRoute = AppReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppReportIdIndexRoute = AppReportIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportIdRoute,
} as any)
const ApiPublicHooksProcessJobsRoute =
  ApiPublicHooksProcessJobsRouteImport.update({
    id: '/api/public/hooks/process-jobs',
    path: '/api/public/hooks/process-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppReportIdReachRoute = AppReportIdReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => AppReportIdRoute,
} as any)
const AppReportIdGrowthRoute = AppReportIdGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppReportIdRoute,
} as any)
const AppReportIdEngagementRoute = AppReportIdEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AppReportIdRoute,
} as any)
const AppReportIdContentRoute = AppReportIdContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppReportIdRoute,
} as any)
const AppReportIdBrandRoute = AppReportIdBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AppReportIdRoute,
} as any)
const AppReportIdAudienceRoute = AppReportIdAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AppReportIdRoute,
} as any)
const AppReportIdAiRoute = AppReportIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppReportIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/analyze': typeof AppAnalyzeRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/top-lists': typeof AppTopListsRoute
  '/tracked': typeof AppTrackedRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/share/$token': typeof ShareTokenRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/report/$id': typeof AppReportIdRouteWithChildren
  '/report/$id/ai': typeof AppReportIdAiRoute
  '/report/$id/audience': typeof AppReportIdAudienceRoute
  '/report/$id/brand': typeof AppReportIdBrandRoute
  '/report/$id/content': typeof AppReportIdContentRoute
  '/report/$id/engagement': typeof AppReportIdEngagementRoute
  '/report/$id/growth': typeof AppReportIdGrowthRoute
  '/report/$id/reach': typeof AppReportIdReachRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
  '/report/$id/': typeof AppReportIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/analyze': typeof AppAnalyzeRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/top-lists': typeof AppTopListsRoute
  '/tracked': typeof AppTrackedRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/share/$token': typeof ShareTokenRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/report/$id/ai': typeof AppReportIdAiRoute
  '/report/$id/audience': typeof AppReportIdAudienceRoute
  '/report/$id/brand': typeof AppReportIdBrandRoute
  '/report/$id/content': typeof AppReportIdContentRoute
  '/report/$id/engagement': typeof AppReportIdEngagementRoute
  '/report/$id/growth': typeof AppReportIdGrowthRoute
  '/report/$id/reach': typeof AppReportIdReachRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
  '/report/$id': typeof AppReportIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/_app/analyze': typeof AppAnalyzeRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/compare': typeof AppCompareRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/top-lists': typeof AppTopListsRoute
  '/_app/tracked': typeof AppTrackedRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/report/$id': typeof AppReportIdRouteWithChildren
  '/_app/report/$id/ai': typeof AppReportIdAiRoute
  '/_app/report/$id/audience': typeof AppReportIdAudienceRoute
  '/_app/report/$id/brand': typeof AppReportIdBrandRoute
  '/_app/report/$id/content': typeof AppReportIdContentRoute
  '/_app/report/$id/engagement': typeof AppReportIdEngagementRoute
  '/_app/report/$id/growth': typeof AppReportIdGrowthRoute
  '/_app/report/$id/reach': typeof AppReportIdReachRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
  '/_app/report/$id/': typeof AppReportIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/analyze'
    | '/campaigns'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/top-lists'
    | '/tracked'
    | '/api/proxy-image'
    | '/share/$token'
    | '/campaigns/$id'
    | '/report/$id'
    | '/report/$id/ai'
    | '/report/$id/audience'
    | '/report/$id/brand'
    | '/report/$id/content'
    | '/report/$id/engagement'
    | '/report/$id/growth'
    | '/report/$id/reach'
    | '/api/public/hooks/process-jobs'
    | '/report/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/analyze'
    | '/campaigns'
    | '/compare'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/top-lists'
    | '/tracked'
    | '/api/proxy-image'
    | '/share/$token'
    | '/campaigns/$id'
    | '/report/$id/ai'
    | '/report/$id/audience'
    | '/report/$id/brand'
    | '/report/$id/content'
    | '/report/$id/engagement'
    | '/report/$id/growth'
    | '/report/$id/reach'
    | '/api/public/hooks/process-jobs'
    | '/report/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/_app/analyze'
    | '/_app/campaigns'
    | '/_app/compare'
    | '/_app/dashboard'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/top-lists'
    | '/_app/tracked'
    | '/api/proxy-image'
    | '/share/$token'
    | '/_app/campaigns/$id'
    | '/_app/report/$id'
    | '/_app/report/$id/ai'
    | '/_app/report/$id/audience'
    | '/_app/report/$id/brand'
    | '/_app/report/$id/content'
    | '/_app/report/$id/engagement'
    | '/_app/report/$id/growth'
    | '/_app/report/$id/reach'
    | '/api/public/hooks/process-jobs'
    | '/_app/report/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicHooksProcessJobsRoute: typeof ApiPublicHooksProcessJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-image': {
      id: '/api/proxy-image'
      path: '/api/proxy-image'
      fullPath: '/api/proxy-image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tracked': {
      id: '/_app/tracked'
      path: '/tracked'
      fullPath: '/tracked'
      preLoaderRoute: typeof AppTrackedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top-lists': {
      id: '/_app/top-lists'
      path: '/top-lists'
      fullPath: '/top-lists'
      preLoaderRoute: typeof AppTopListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyze': {
      id: '/_app/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report/$id': {
      id: '/_app/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AppReportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/report/$id/': {
      id: '/_app/report/$id/'
      path: '/'
      fullPath: '/report/$id/'
      preLoaderRoute: typeof AppReportIdIndexRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/api/public/hooks/process-jobs': {
      id: '/api/public/hooks/process-jobs'
      path: '/api/public/hooks/process-jobs'
      fullPath: '/api/public/hooks/process-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/report/$id/reach': {
      id: '/_app/report/$id/reach'
      path: '/reach'
      fullPath: '/report/$id/reach'
      preLoaderRoute: typeof AppReportIdReachRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/_app/report/$id/growth': {
      id: '/_app/report/$id/growth'
      path: '/growth'
      fullPath: '/report/$id/growth'
      preLoaderRoute: typeof AppReportIdGrowthRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/_app/report/$id/engagement': {
      id: '/_app/report/$id/engagement'
      path: '/engagement'
      fullPath: '/report/$id/engagement'
      preLoaderRoute: typeof AppReportIdEngagementRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/_app/report/$id/content': {
      id: '/_app/report/$id/content'
      path: '/content'
      fullPath: '/report/$id/content'
      preLoaderRoute: typeof AppReportIdContentRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/_app/report/$id/brand': {
      id: '/_app/report/$id/brand'
      path: '/brand'
      fullPath: '/report/$id/brand'
      preLoaderRoute: typeof AppReportIdBrandRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/_app/report/$id/audience': {
      id: '/_app/report/$id/audience'
      path: '/audience'
      fullPath: '/report/$id/audience'
      preLoaderRoute: typeof AppReportIdAudienceRouteImport
      parentRoute: typeof AppReportIdRoute
    }
    '/_app/report/$id/ai': {
      id: '/_app/report/$id/ai'
      path: '/ai'
      fullPath: '/report/$id/ai'
      preLoaderRoute: typeof AppReportIdAiRouteImport
      parentRoute: typeof AppReportIdRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppReportIdRouteChildren {
  AppReportIdAiRoute: typeof AppReportIdAiRoute
  AppReportIdAudienceRoute: typeof AppReportIdAudienceRoute
  AppReportIdBrandRoute: typeof AppReportIdBrandRoute
  AppReportIdContentRoute: typeof AppReportIdContentRoute
  AppReportIdEngagementRoute: typeof AppReportIdEngagementRoute
  AppReportIdGrowthRoute: typeof AppReportIdGrowthRoute
  AppReportIdReachRoute: typeof AppReportIdReachRoute
  AppReportIdIndexRoute: typeof AppReportIdIndexRoute
}

const AppReportIdRouteChildren: AppReportIdRouteChildren = {
  AppReportIdAiRoute: AppReportIdAiRoute,
  AppReportIdAudienceRoute: AppReportIdAudienceRoute,
  AppReportIdBrandRoute: AppReportIdBrandRoute,
  AppReportIdContentRoute: AppReportIdContentRoute,
  AppReportIdEngagementRoute: AppReportIdEngagementRoute,
  AppReportIdGrowthRoute: AppReportIdGrowthRoute,
  AppReportIdReachRoute: AppReportIdReachRoute,
  AppReportIdIndexRoute: AppReportIdIndexRoute,
}

const AppReportIdRouteWithChildren = AppReportIdRoute._addFileChildren(
  AppReportIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCompareRoute: typeof AppCompareRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTopListsRoute: typeof AppTopListsRoute
  AppTrackedRoute: typeof AppTrackedRoute
  AppReportIdRoute: typeof AppReportIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCompareRoute: AppCompareRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTopListsRoute: AppTopListsRoute,
  AppTrackedRoute: AppTrackedRoute,
  AppReportIdRoute: AppReportIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicHooksProcessJobsRoute: ApiPublicHooksProcessJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
