
-- Influencers table
CREATE TABLE public.influencers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  profile_url text,
  platform text,
  influencer_name text,
  username text,
  profile_pic_url text,
  biography text,
  is_verified boolean DEFAULT false,
  followers integer DEFAULT 0,
  following integer DEFAULT 0,
  posts_count integer DEFAULT 0,
  avg_views integer DEFAULT 0,
  avg_likes integer DEFAULT 0,
  avg_comments integer DEFAULT 0,
  avg_shares integer DEFAULT 0,
  avg_saves integer DEFAULT 0,
  engagement_rate numeric DEFAULT 0,
  country text,
  city text,
  primary_language text,
  niche text,
  sub_niche text,
  audience_gender_split jsonb,
  audience_age_groups jsonb,
  audience_top_country text,
  audience_top_cities text,
  audience_languages jsonb,
  audience_quality_score integer DEFAULT 0,
  audience_authenticity_score integer DEFAULT 0,
  fake_followers_score integer DEFAULT 0,
  suspicious_engagement_score integer DEFAULT 0,
  inactive_followers_score integer DEFAULT 0,
  follower_growth_30d numeric DEFAULT 0,
  follower_growth_90d numeric DEFAULT 0,
  engagement_growth numeric DEFAULT 0,
  viral_frequency_score integer DEFAULT 0,
  avg_reach integer DEFAULT 0,
  avg_impressions integer DEFAULT 0,
  avg_view_rate numeric DEFAULT 0,
  avg_completion_rate numeric DEFAULT 0,
  avg_watch_time numeric DEFAULT 0,
  top_performing_format text,
  top_performing_hook_type text,
  top_performing_content_style text,
  conversion_intent_score integer DEFAULT 0,
  trust_score integer DEFAULT 0,
  recommendation_power_score integer DEFAULT 0,
  audience_purchase_intent_score integer DEFAULT 0,
  ad_reusability_score integer DEFAULT 0,
  positive_comment_ratio numeric DEFAULT 0,
  negative_comment_ratio numeric DEFAULT 0,
  buying_comments_ratio numeric DEFAULT 0,
  trust_comments_ratio numeric DEFAULT 0,
  best_campaign_goal text,
  best_brand_fit text,
  strongest_niche_fit text,
  strongest_season_fit text,
  strongest_platform text,
  creator_style text,
  filming_style text,
  editing_style text,
  pacing_style text,
  storytelling_style text,
  avg_collab_price integer DEFAULT 0,
  post_price_min integer DEFAULT 0,
  post_price_estimated integer DEFAULT 0,
  post_price_max integer DEFAULT 0,
  story_price_min integer DEFAULT 0,
  story_price_estimated integer DEFAULT 0,
  story_price_max integer DEFAULT 0,
  reel_price_min integer DEFAULT 0,
  reel_price_estimated integer DEFAULT 0,
  reel_price_max integer DEFAULT 0,
  reliability_score integer DEFAULT 0,
  posting_consistency text,
  controversy_score integer DEFAULT 0,
  overpromotion_score integer DEFAULT 0,
  audience_mismatch_risk integer DEFAULT 0,
  inconsistency_risk integer DEFAULT 0,
  brand_safety_score integer DEFAULT 0,
  overall_score integer DEFAULT 0,
  top_niches jsonb,
  creator_brand_affinity jsonb,
  follower_brand_affinity jsonb,
  interest_categories jsonb,
  psychological_traits jsonb,
  sentiment_positive numeric DEFAULT 0,
  sentiment_neutral numeric DEFAULT 0,
  sentiment_negative numeric DEFAULT 0,
  sentiment_verdict text,
  sentiment_net_score integer DEFAULT 0,
  trending_topics jsonb,
  word_cloud jsonb,
  top_hashtags jsonb,
  top_mentions jsonb,
  best_time_to_post jsonb,
  ai_summary text,
  ai_strengths text,
  ai_weaknesses text,
  ai_recommendation text,
  best_for_tags jsonb,
  collab_tips jsonb,
  recent_posts jsonb,
  popular_posts jsonb,
  raw_apify_data jsonb
);

CREATE TABLE public.apify_tools (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id text NOT NULL,
  label text NOT NULL,
  platform text NOT NULL,
  is_enabled boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_name text DEFAULT 'Boom Teams',
  apify_api_key text,
  gemini_api_key text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Single settings row
INSERT INTO public.settings (team_name) VALUES ('Boom Teams');

-- Permissive RLS — single tenant internal tool with hardcoded auth
ALTER TABLE public.influencers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apify_tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public all" ON public.influencers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public all" ON public.apify_tools FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public all" ON public.settings FOR ALL USING (true) WITH CHECK (true);
